{"componentChunkName":"component---src-templates-tags-js","path":"/tags/exceptions/","result":{"data":{"allMdx":{"totalCount":1,"edges":[{"node":{"frontmatter":{"title":"python try-except 에러처리에 대해 알아보자","url_path":"/blog/2020/06/21/python-try-except-에러처리에-대해-알아보자","tags":["python","Try-except","Exceptions","Errors"],"date":"2020-06-22T01:57:00"},"fields":{"readingTime":{"text":"6 min read"}}}}]}},"pageContext":{"tag":"Exceptions"}}}